In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [2]:
df = pd.read_csv("./iterative_imputation_practice.csv")
df.sample(5)

,Age,Experience_Years,Education_Years,Hours_Per_Week,Projects_Completed,Salary
5,27.0,5.0,NaN,35.0,7.0,124791.0
23,35.0,13.0,17.0,37.0,2.0,153688.0
26,40.0,8.0,15.0,36.0,5.0,144714.0
17,NaN,3.0,12.0,47.0,4.0,128232.0
20,30.0,15.0,12.0,50.0,10.0,189462.0

In [4]:
df.isnull().sum()

Age                   4
Experience_Years      4
Education_Years       4
Hours_Per_Week        4
Projects_Completed    4
Salary                0
dtype: int64

In [3]:
X = df.drop(columns=["Salary"])
y = df["Salary"]

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

In [17]:
imputer = IterativeImputer(max_iter=5, random_state=2)

In [18]:
X_train_impute = imputer.fit_transform(X_train)
X_test_impute = imputer.transform(X_test)

In [19]:
pd.DataFrame(X_train_impute, columns=X_train.columns)

,Age,Experience_Years,Education_Years,Hours_Per_Week,Projects_Completed
0,39.000000,6.000000,16.000000,40.000000,3.000000
1,24.000000,8.753337,13.000000,35.000000,6.000000
2,30.374127,3.000000,12.000000,47.000000,4.000000
3,22.000000,9.000000,18.000000,41.000000,10.000000
4,23.000000,13.000000,17.000000,44.000000,1.000000
5,38.000000,14.000000,18.000000,46.000000,5.106551
6,21.000000,13.000000,18.000000,45.000000,9.000000
7,35.000000,1.000000,18.000000,49.000000,5.113908
8,32.000000,11.000000,14.000000,43.461003,1.000000
9,26.000000,1.000000,12.000000,47.000000,5.118988
10,27.000000,15.000000,12.000000,43.000000,1.000000
11,27.000000,5.000000,15.135111,35.000000,7.000000
12,27.000000,1.000000,16.000000,40.000000,2.000000
13,40.000000,3.000000,15.000000,37.000000,9.000000
14,39.000000,4.000000,14.000000,48.000000,1.000000
15,34.000000,7.000000,14.000000,46.000000,5.000000
16,27.000000,12.000000,15.134151,50.000000,10.000000
17,37.000000,14.000000,15.140280,47.000000,1.000000
18,29.000000,8.000000,16.000000,38.000000,1.000000
19,28.000000,14.000000,16.000000,48.000000,1.000000
20,28.000000,5.000000,14.000000,41.000000,3.000000
21,39.000000,9.000000,14.000000,38.000000,6.000000
22,30.359612,13.000000,14.000000,50.000000,9.000000
23,30.000000,15.000000,12.000000,50.000000,10.000000
24,40.000000,8.000000,15.000000,36.000000,5.000000
25,22.000000,11.000000,13.000000,48.000000,3.000000
26,36.000000,14.000000,18.000000,41.000000,4.000000
27,32.000000,8.000000,18.000000,44.000000,5.110959
28,30.386966,12.000000,14.000000,39.000000,2.000000
29,24.000000,4.000000,17.000000,46.000000,7.000000
30,31.000000,8.757843,14.000000,47.000000,8.000000
31,38.000000,8.000000,15.000000,35.000000,8.000000
32,23.000000,1.000000,13.000000,43.494448,3.000000
33,32.000000,13.000000,15.000000,38.000000,1.000000
34,28.000000,12.000000,14.000000,41.000000,7.000000
35,35.000000,8.756717,18.000000,45.000000,7.000000
36,31.000000,5.000000,12.000000,50.000000,9.000000
37,23.000000,12.000000,18.000000,43.000000,7.000000
38,22.000000,9.000000,15.000000,49.000000,8.000000
39,35.000000,11.000000,18.000000,45.000000,5.000000

In [20]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [21]:
lr = LinearRegression()

lr.fit(X_train_impute, y_train)

y_pred = lr.predict(X_test_impute)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("MSE:", mse)
print("R2 Score:", r2)

MAE: 4251.914055801874
MSE: 24406630.564017233
R2 Score: 0.8480283847527291